"""empty message

Revision ID: 2def932bba27
Revises: dbb1ae1fc321
Create Date: 2021-02-20 16:24:26.961122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2def932bba27'
down_revision = 'dbb1ae1fc321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist', type_='unique')
    # ### end Alembic commands ###
