"""empty message

Revision ID: 7c6eb087773d
Revises: adad74aa6191
Create Date: 2021-02-22 20:41:14.436108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6eb087773d'
down_revision = 'adad74aa6191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'upcoming')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('upcoming', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
