"""empty message

Revision ID: dbb1ae1fc321
Revises: 4b830571ba5f
Create Date: 2021-02-20 16:23:13.880162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb1ae1fc321'
down_revision = '4b830571ba5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Venue', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    # ### end Alembic commands ###
